### PR TITLE
Nmr item form

### PR DESCRIPTION
**Pull request by nishayaraj**

### CODE REVIEW

**Comment by nishayaraj** [comment]
item form, add payment form, minute changes in add order form

**Review by gitNitroTitan — CHANGES_REQUESTED** [review]
just a < needed in front of value below the closing select tag.

**Review by gitNitroTitan — APPROVED** [review]
beautiful :)

**Comment by nishayaraj** [comment]
> just a < needed in front of value below the closing select tag.

did that. thank you

**Review by lesleyjkeyes — APPROVED** [review]
looks good!

**Pull request merged**
